import { enUS, type Catalog } from "./en-US.js";

export const zhCN: Catalog = {
  ...enUS,
  "home.defaultRoomName": "{{name}} 的房间", "home.defaultPlayerName": "玩家",
  "chat.close": "关闭聊天",
  "game.swapTitle": "与 {{name}} 交换？", "game.swapBody": "你的第 {{own}} 张牌将与 {{name}} 的第 {{position}} 张牌盲换，两张牌都不会公开。", "game.table": "牌桌",
  "game.yourHandActions": "你的手牌和操作",
  "settings.trigger": "设置", "settings.title": "设置", "settings.theme": "主题", "settings.language": "语言", "settings.auto": "跟随系统", "settings.light": "浅色", "settings.dark": "深色",
  "nav.main": "主导航", "nav.play": "开始游戏", "nav.rules": "规则", "nav.agent": "智能体",
  "common.close": "关闭", "common.cancel": "取消", "common.leave": "离开", "common.points": "{{count}} 分", "common.seconds": "{{count}} 秒", "common.secondsRemaining": "剩余 {{count}} 秒", "common.unknownError": "出现错误{{code}}，请重试。",
  "home.kicker": "在线牌桌", "home.title": "保持最低手牌。\n相信你的记忆。", "home.lede": "适合二至五人的安静实时牌桌。", "home.reconnecting": "正在重新连接已保存的座位…", "home.playCabo": "玩 Cabo", "home.quickStart": "快速开始", "home.playerName": "玩家名称", "home.yourName": "你的名字", "home.createRoom": "创建房间", "home.joinByCode": "使用代码加入", "home.public": "公开", "home.private": "私密", "home.roomVisibility": "房间可见性", "home.roomName": "房间名称", "home.roomNameHint": "最多 40 个字符", "home.targetScore": "目标分数", "home.memoryMode": "记忆模式", "home.classic": "经典 — 自己记住牌面", "home.assisted": "辅助 — 保持已看牌可见", "home.stepTimer": "步骤计时", "home.unlimited": "不限时", "home.passwordSix": "六位数字密码", "home.createTable": "创建牌桌", "home.invitationServer": "邀请服务器：", "home.invitationConfirm": "加入牌桌以确认。", "home.roomCode": "房间代码", "home.password": "密码", "home.optional": "可选", "home.joinTable": "加入牌桌", "home.openTables": "开放牌桌", "home.publicRooms": "公开房间", "home.refresh": "刷新", "home.refreshing": "刷新中…", "home.roomSummary": "房间 {{id}} · 目标 {{score}} · {{mode}} · {{timer}}", "home.roomState": "{{capacity}} · {{state}} · {{count}} / {{max}} 位玩家", "home.full": "已满", "home.open": "开放", "home.started": "已开始", "home.waiting": "等待中", "home.join": "加入", "home.noRooms": "还没有公开房间，来创建第一个吧。", "home.serverSettings": "服务器设置", "home.gameServer": "游戏服务器", "home.apply": "应用", "home.resetTo": "重置为 {{url}}",
  "session.connectionLost": "连接已断开，你的座位将保留 60 秒。", "session.connectionRestored": "连接已恢复。", "session.saveFailed": "此浏览器无法保存重连会话。", "session.expired": "保存的座位已过期，请加入房间继续游戏。", "session.enterName": "请输入玩家名称。", "session.serverUpdated": "服务器已更新。", "session.serverReset": "服务器已重置为 {{url}}。", "session.nicknameTaken": "该玩家名称已被使用。", "session.invalidPassword": "房间密码不正确。", "session.notHost": "只有房主可以执行此操作。", "session.notEnoughPlayers": "至少需要两位已连接玩家。", "session.notYourTurn": "现在不是你的回合。", "session.invalidPhase": "当前不能执行此操作。", "session.chatRateLimited": "消息发送过快，请稍后再试。", "session.readOnly": "此座位已在另一个标签页中打开，本页操作已暂停。", "session.takeOver": "在此接管",
  "connection.live": "在线", "connection.connecting": "连接中", "connection.reconnecting": "重连中", "connection.offline": "离线", "connection.ready": "就绪",
  "chat.trigger": "聊天", "chat.unread": "聊天，{{count}} 条未读消息", "chat.unread_other": "聊天，{{count}} 条未读消息", "chat.paused": "本标签页的聊天已暂停", "chat.reconnecting": "重连期间无法聊天", "chat.unavailable": "聊天不可用", "chat.room": "房间聊天", "chat.ephemeral": "临时消息 · 不会保存", "chat.empty": "暂无消息。", "chat.you": "你", "chat.message": "消息", "chat.placeholder": "说点什么…", "chat.send": "发送", "chat.enter": "请输入消息。", "chat.tooLong": "消息最多 200 个字符。",
  "room.share": "分享", "room.copyCode": "复制房间代码", "room.copyLink": "复制邀请链接", "room.copied": "已复制", "room.copyManually": "手动复制", "room.lobbyTitle": "牌桌即将准备就绪。", "room.lobbyDetail": "分享区分大小写的房间代码。至少两位玩家连接后，房主即可开始。", "room.you": "你", "room.host": "房主", "room.ready": "就绪", "room.offline": "离线", "room.openSeat": "空座位", "room.start": "开始游戏", "room.waitPlayers": "等待玩家…", "room.waitHost": "等待房主…", "room.quickRules": "快速规则", "room.fullRules": "阅读完整规则", "room.rules1": "保持最低总分。从牌堆抽牌、拿取弃牌，或呼叫 Cabo。", "room.rules2": "一张抽到的牌可替换 1–4 张牌；选择 2–4 张时必须同点数。匹配失败会亮出这些牌，并可能增加一张罚牌。", "room.rules3": "7–8 可查看自己的牌；9–10 可查看另一位玩家的牌。", "room.rules4": "J–Q 可将自己的任意一张牌与另一位玩家的任意一张牌盲换。", "room.rules5": "呼叫 Cabo 后，其他人各有最后一回合。成功呼叫者得 0 分。", "room.rules6": "恰好两张 Q 和两张 K 可射月：你得 0 分，其他人各得目标分数的一半。",
  "game.otherPlayers": "其他玩家", "game.cards": "{{count}} 张牌", "game.drawnCard": "抽到的牌", "game.deck": "牌堆", "game.discard": "弃牌堆", "game.empty": "空", "game.callCabo": "呼叫 Cabo", "game.yourHand": "你的手牌", "game.knownHidden": "已知 {{known}} · 隐藏 {{hidden}}", "game.recent": "最近动态", "game.quiet": "牌桌很安静。", "game.scores": "分数", "game.roundArchive": "回合记录", "game.everyPoint": "每手牌，每一分。", "game.completedRounds": "已完成 {{count}} 回合", "game.completedRounds_other": "已完成 {{count}} 回合", "game.player": "玩家", "game.round": "第 {{count}} 回合", "game.noHistory": "完成的回合会在这里向牌桌上的所有人显示。", "game.privateReveal": "私密翻牌", "game.forEyesOnly": "仅供你查看", "game.closingAutomatically": "即将自动关闭",
  "game.dnf": "弃权", "game.offlineGrace": "离线 · 保留 60 秒", "game.chooseCard": "选择 {{name}} 的牌", "game.drawPile": "牌堆，{{count}} 张牌", "game.discardPile": "弃牌堆，{{card}}", "game.discardPositions": "弃掉位置：{{positions}} · 抽牌放到 → {{destination}}", "game.choose": "请选择", "game.drawDestination": "抽牌放置位置", "game.choosePosition": "选择位置", "game.confirmExchange": "确认交换", "game.clear": "清除", "game.noCards": "没有牌可抽。", "game.finishFinal": "结束最后回合", "game.waiting": "等待中", "game.chooseOwnSwap": "选择要交换的自己的牌。", "game.thenChoose": "然后选择另一位玩家及其任意一张牌。", "game.blindSwap": "盲换", "game.privatePeek": "私密查看", "game.chooseTheirCard": "选择对方的一张牌。", "game.choosePlayer": "选择另一位玩家。", "game.neitherRevealed": "两张牌都不会亮出。", "game.onlyYouSee": "只有你能看到所选的牌。", "game.cardDrawn": "已抽牌", "game.chooseReplace": "选择要替换的牌。", "game.selectUpTo": "直接从手牌中选择最多四张；多张牌必须点数相同。", "game.discardDrawn": "弃掉抽到的牌", "game.mismatch": "牌面不匹配", "game.placeDrawn": "放置抽到的牌。", "game.selectedPublic": "所选牌现已公开。", "game.leftEnd": "左端", "game.rightEnd": "右端", "game.penaltyCard": "罚牌", "game.placePenalty": "放置面朝下的罚牌。", "game.drawnGoes": "抽到的牌将放到{{side}}。", "game.back": "返回", "game.memoryPower": "记忆能力", "game.peekOwn": "查看自己的一张牌。", "game.chooseOrSkip": "选择一个位置，或跳过能力。", "game.skipPower": "跳过能力", "game.insightPower": "洞察能力", "game.peekOther": "查看另一位玩家的一张牌。", "game.exchangePower": "交换能力", "game.blindSwapAny": "盲换任意两个位置。", "game.chooseYourCard": "选择你的牌", "game.skip": "跳过", "game.noPower": "无能力", "game.continueTable": "继续游戏。", "game.continue": "继续", "game.yourTurn": "你的回合", "game.drawIntention": "谨慎抽牌。", "game.takeHidden": "从牌堆抽取隐藏牌、选择弃牌，或呼叫 Cabo。", "game.status.roundComplete": "回合结束", "game.status.countCards": "清点手牌。", "game.status.nextReady": "所有有效玩家准备后开始下一回合。", "game.status.matchComplete": "比赛结束", "game.status.tableSpoken": "牌桌已有定论。", "game.status.reviewScores": "查看最终分数。", "game.status.finalTurns": "最后回合", "game.status.inPlay": "游戏中", "game.status.playerTurn": "{{name}} 的回合", "game.status.watch": "观察牌桌并记住变化。", "game.status.drawn": "你的回合 · 已抽牌", "game.status.exchange": "进行交换。", "game.status.replace": "替换 1–4 张牌{{discard}}。", "game.status.orDiscard": "，或弃掉抽牌", "game.status.mismatch": "你的回合 · 不匹配", "game.status.placePenalty": "放置罚牌。", "game.status.cardsPublic": "所选牌已公开；选择新牌的位置。", "game.status.power": "你的回合 · 能力", "game.status.useRevealed": "使用亮出的能力。", "game.status.resolvePower": "执行卡牌能力或跳过。", "game.status.finalTurn": "你的最后回合", "game.status.chooseDraw": "选择抽牌位置。", "game.status.drawDetail": "牌堆隐藏可能，弃牌提供确定。",
  "game.risk.cards": "你的手中有 {{count}} 张牌。", "game.risk.exact": "手牌准确总分：{{score}}。", "game.risk.subtotal": "已知小计：{{score}}；另有 {{count}} 张未知牌。", "game.risk.rules": "你的分数必须严格最低，平分也算失败。失败时计入手牌分数并加 {{penalty}} 分。其他有效玩家各有最后一个回合。",
  "event.joined": "{{name}} 加入了牌桌。", "event.disconnected": "{{name}} 已离线。", "event.reconnected": "{{name}} 已重新连接。", "event.turn": "{{name}} 正在出牌。", "event.finalTurn": "{{name}} 正在进行最后一回合。", "event.timeout": "{{name}} 已超时；服务器完成了其回合。", "event.forfeit": "{{name}} 已弃权。", "event.drawDeck": "{{name}} 从牌堆抽了一张隐藏牌。", "event.drawDiscard": "{{name}} 从弃牌堆拿走了 {{card}}。", "event.replace": "{{name}} 替换了位置 {{positions}}；抽到的牌放在位置 {{position}}。", "event.exchangeMismatch": "{{name}} 选择的牌不匹配，现已公开。", "event.resolveMismatch": "{{name}} 将不匹配的牌放到了所选两端。", "event.discard": "{{name}} 弃掉了抽到的 {{card}}。", "event.peekSelf": "{{name}} 查看了自己的第 {{position}} 张牌。", "event.peekOther": "{{name}} 查看了 {{target}} 的第 {{position}} 张牌。", "event.swap": "{{name}} 将自己的第 {{own}} 张牌与 {{target}} 的第 {{position}} 张牌交换。", "event.skip": "{{name}} 跳过了卡牌能力。", "event.cabo": "{{name}} 呼叫了 Cabo。",
  "result.matchComplete": "比赛结束", "result.winners": "{{names}}{{verb}}了本桌比赛。", "result.share": "共同赢得", "result.takes": "赢得", "result.leaving": "离开中…", "result.back": "返回房间", "result.roundComplete": "第 {{count}} 回合结束", "result.moon": "{{name}} 射月成功。", "result.caboSucceeded": "Cabo 呼叫成功。", "result.caboChallenged": "Cabo 呼叫被挑战。", "result.confirm": "准备好继续时请确认。", "result.fallback": "私密结果在本页重连前已到达；所有人确认下一回合期间显示当前总分。", "result.readyCount": "{{ready}} / {{count}} 位有效玩家已准备", "result.waitOthers": "等待其他人…", "result.confirming": "确认中…", "result.readyNext": "准备下一回合", "result.nextIn": "{{count}} 秒后开始下一回合",
  "modal.table": "Cabo 牌桌", "modal.leaveRoomTitle": "离开此房间？", "modal.leaveRoomBody": "你的座位将被释放。", "modal.leaveRoomAction": "离开房间", "modal.leaveMatchTitle": "离开比赛？", "modal.leaveMatchBody": "离开进行中的比赛将被视为弃权。", "modal.leaveMatchAction": "弃权并离开",
  "docs.title": "Cabo 文档", "docs.onPage": "本页内容", "docs.footer": "Cabo 是一款由服务器判定状态的在线牌桌。", "docs.source": "GitHub 源码", "docs.rules.title": "保持最低手牌。", "docs.rules.lede": "Cabo 是一款适合二至五人的记忆游戏。了解必要信息，记住关键牌面，并在正确时机结束回合。", "docs.cli.title": "在命令行中玩 Cabo。", "docs.cli.lede": "交互式终端客户端提供与 Web 牌桌相同的房间、私密记忆、合法操作和重连能力。", "docs.agent.title": "用任意语言驱动 Cabo。", "docs.agent.lede": "cabo-agent 通过标准输入输出，以与语言无关的 JSONL 子进程运行一位玩家。", "docs.goal": "目标与设置", "docs.turns": "进行回合", "docs.powers": "卡牌能力", "docs.cabo": "呼叫 Cabo", "docs.connections": "连接", "docs.install": "安装与启动", "docs.connectionCommands": "连接命令", "docs.lobbyCommands": "大厅命令", "docs.gameCommands": "游戏命令", "docs.interaction": "交互说明", "docs.startAgent": "启动智能体", "docs.transport": "进程契约", "docs.loop": "监督循环", "docs.state": "状态与恢复", "docs.lifecycle": "会话与关闭"
};
